name: docker-image
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build the docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:$(date +%s)
